# https://developers.google.com/appengine/docs/python/config/appconfig

application: fg-blog-hr
version: pelican-1
runtime: python27
api_version: 1
threadsafe: false


handlers:

  - url: /\d+/\d+/[^\d][^/]+/?
    script: dynamic.legacy_redirect.app

  - url: /_ereporter.*
    script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
    login: admin

  - url: /(favicon\.ico|robots\.txt)
    static_files: output/static/misc/\1
    upload: output/static/misc/(favicon\.ico|robots\.txt)

  - url: /
    static_files: output/index.html
    upload: output/index\.html

  - url: /theme/css/(.*\.ttf)
    static_files: output/theme/css/\1
    upload: output/theme/css/(.*\.ttf)
    mime_type: application/x-font-ttf

  - url: /misc/(.*\.(patch|go))
    static_files: output/misc/\1
    upload: output/misc/(.*\.(patch|go))
    mime_type: text/plain

  - url: /
    static_dir: output


# builtins:
#   - datastore_admin: on
#   - appstats: on
#   - remote_api: on


# pagespeed:
#   domains_to_rewrite:
#   - www.foo.com
#   - https://*.secure.foo.com
#   url_blacklist:
#   - http://myapp.com/blob/*
#   - http://myapp.com/comments/*
#   enabled_rewriters:
#   - MinifyCss
#   disabled_rewriters:
#   - ImageStripColorProfile


skip_files:
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?\..*$

  - ^(themes|content)/
  - ^[^/]*conf\.py$
  - ^[^/]+\.(yaml|txt|sh)$
  - ^Makefile|README\.md|COPYING$
